### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by konklone** [esevece/esevece.github.io#2]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS without errors: https://esevece.github.io So this should be a trivial fix.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by esevece** [comment]
@konklone thank you! I wasn't aware of that new feature.
Best :smile:

**Comment by konklone** [comment]
Awesome, thanks! :smiley_cat:

**Comment by esevece** [comment]
Thank you!
